api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
    api_keys:
      apiKey: # Add form input to set bearer Token on Authorize button on Swagger UI
        name: Authorization
        type: header
  collection:
    pagination:
      enabled: false
