api_platform:
  title: "API BileMo"
  # The description of the API.
  description: "L'authentification se fait sur api/login_check<br /><br />Informations sur les actions autorisées en fonction des rôles : <br />- Utilisateur anonyme : Peut s'authentifier<br />- Utilisateur authentifié : Peut consulter les produits, créer / supprimer / modifier un client"

  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
    api_keys:
      apiKey: # Add form input to set bearer Token on Authorize button on Swagger UI
        name: Authorization
        type: header
  collection:
    pagination:
      enabled: false
